export const photoConstants = {
  PHOTO_GET_IMAGE_SIZE: 'PHOTO_GETIMAGESIZE',
  PHOTO_GET_IMAGE_INFO: 'PHOTO_GET_IMAGE_INFO',
  PHOTO_GET_FAV: 'PHOTO_GET_FAV',
  PHOTO_SET_LOADING: 'PHOTO_SET_LOADING',

}
